server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaweb
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.lession13springbootmybatis.dao
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl