server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl