spring:
  application:
    name: StarWhisper_Server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/starwhisper?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
  mail:
    host: smtp.126.com
    username: tlk_sure@126.com
    password: TJhzZdbL4BkNXJtN
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 3000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.starwhisper_server.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  secret: your_jwt_secret
  expiration: 3600000

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.deepseek.com
